/* Automatically generated by configure - do not modify */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "/usr/local/lib/tcc"
#endif
#ifndef CONFIG_TCC_PREDEFS
# define CONFIG_TCC_PREDEFS 0
#endif
#define TCC_VERSION "0.9.27"
#define GCC_MAJOR 5
#define GCC_MINOR 4
#define CC_NAME CC_gcc
